### ISSUE TITLE
BadPFMuonFilter error

### ISSUE THREAD

**Issue by stremreich** [kdlong/UWVV#5]
The following command:
``cmsRun Ntuplizer/test/ntuplize_cfg.py channels='zz' isMC=1 genInfo=1 globalTag=80X_mcRun2_asymptotic_2016_TrancheIV_v8 genLeptonType=dressedHPFS lheWeights=2 inputFiles=/store/mc/RunIISummer16MiniAODv2/ZZTo4L_13TeV_powheg_pythia8/MINIAODSIM/PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/120000/267B458E-19C5-E611-8FCB-001E6757E05C.root outputFile=ntuple.root``

...gives the following error on the current master branch of UWVV:
``----- Begin Fatal Exception 30-Nov-2017 00:39:13 CST-----------------------
An exception of category 'ConfigFileReadError' occurred while
  [0] Processing the python configuration file named Ntuplizer/test/ntuplize_cfg.py
Exception Message:
python encountered the error: <type 'exceptions.ImportError'>
No module named BadPFMuonFilter_cfi
----- End Fatal Exception -------------------------------------------------``

**Comment by kdlong** [comment]
I'm checking with the master version on uwcms/UWVV and I don't see this error. From CMSSW_8_0_30/src/UWVV, I do:

```
git remote add upstream git@github.com:uwcms/UWVV.git
git fetch upstream
git merge upstream/master
cd ..
scram b
cd UWVV
cmsRun Ntuplizer/test/ntuplize_cfg.py channels='zz' isMC=1 genInfo=1 globalTag=80X_mcRun2_asymptotic_2016_TrancheIV_v8 genLeptonType=dressedHPFS lheWeights=2 inputFiles=/store/mc/RunIISummer16MiniAODv2/ZZTo4L_13TeV_powheg_pythia8/MINIAODSIM/PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/120000/267B458E-19C5-E611-8FCB-001E6757E05C.root outputFile=ntuple.root
```

and for me it works as expected. The error looks a lot like the name of a file got changed but not updated in the config file. It at least seems to me like this a temporary mistake which got fixed, but maybe you synced with the master version in between the error being introduced and fixed?

**Comment by stremreich** [comment]
OK, I'll update UWVV again and see if that was the issue.

**Comment by stremreich** [comment]
Update, I still get the above error when doing the following:

```
scram pro -n uwvv CMSSW CMSSW_8_0_26_patch2
cd uwvv/src
cmsenv
git cms-init
git clone --recursive https://github.com/nwoods/UWVV.git 
cd UWVV
source recipe/setup.sh 
pushd ..
scram b -j 8
popd
cmsRun Ntuplizer/test/ntuplize_cfg.py channels='zz' isMC=1 genInfo=1 globalTag=80X_mcRun2_asymptotic_2016_TrancheIV_v8 genLeptonType=dressedHPFS lheWeights=2 inputFiles=/store/mc/RunIISummer16MiniAODv2/ZZTo4L_13TeV_powheg_pythia8/MINIAODSIM/PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/120000/267B458E-19C5-E611-8FCB-001E6757E05C.root outputFile=ntuple.root
```

and when using the method you used above from the UWVV directory. I tried using your CMSSW version as well just to make sure. The only errors/warnings I saw during the installation process referred to the cut matrix element correction stuff being absent.

**Comment by kdlong** [comment]
Aaah ok, I think the problem is that the MET packages needed for this weren't downloaded by default. I changed things in the setup script so that now the default is to download them. Can you try with this commit: https://github.com/uwcms/UWVV/pull/3

I also changed the recommended CMSSW version to CMSSW_8_0_30

**Comment by stremreich** [comment]
Yep, that did it. Good stuff.
